# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
  database_host: 127.0.0.1
  database_port: 3306
  database_name: todo
  database_user: root
  database_password: pass1234
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null
  secret: dezdzedd2343243CZECZECE!!!xaa
  database_test_host: 127.0.0.1
  database_test_port: 3306
  database_test_name: "todo_test"
  database_test_user: "root"
  database_test_password: "pass1234"

  #    parameter_name: value
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

